[build]
builder = "DOCKERFILE"

[[services]]
name = "backend"
rootDirectory = "/"
dockerfilePath = "PrimeGift/backend/Dockerfile"

[services.env]
PORT = "8000"

[[services]]
name = "frontend"
rootDirectory = "/"
dockerfilePath = "PrimeGift/frontend/Dockerfile"

[services.env]
PORT = "3000"
