[build]
builder = "DOCKERFILE"

[[services]]
name = "backend"
rootDirectory = "/"
dockerfilePath = "backend.Dockerfile"

[services.env]
PORT = "8000"

[[services]]
name = "frontend"
rootDirectory = "/"
dockerfilePath = "frontend.Dockerfile"

[services.env]
PORT = "3000"
